version: '3'


services:
 traitor:
      build: .
      ports:
        - "8080:8080"     
      volumes:
          - "~/.traitor:/root/.traitor"
      container_name: "latest"
      environment:
        -  GIN_MODE=release    